export const ADD_CATEGORY_FILTER = 'ADD_CATEGORY_FILTER'
export const ADD_BRAND_FILTER = 'ADD_BRAND_FILTER'
export const ADD_PRICE_FILTER = 'ADD_PRICE_FILTER'

export const REMOVE_CATEGORY_FILTER = 'REMOVE_CATEGORY_FILTER'
export const REMOVE_BRAND_FILTER = 'REMOVE_BRAND_FILTER'
export const REMOVE_PRICE_FILTER = 'REMOVE_PRICE_FILTER'

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'

export const SELECT_SORT_TYPE = 'SELECT_SORT_TYPE'
export const CHANGE_COLUMN_SIZE = 'CHANGE_COLUMN_SIZE'
