export const ADD_CATEGORY_FILTER = 'ADD_CATEGORY_FILTER'
export const ADD_BRAND_FILTER = 'ADD_BRAND_FILTER'
export const REMOVE_CATEGORY_FILTER = 'REMOVE_CATEGORY_FILTER'
export const REMOVE_BRAND_FILTER = 'REMOVE_BRAND_FILTER'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'

export const SELECT_SORT_TYPE = 'SELECT_SORT_TYPE'
export const CHANGE_COLUMN_SIZE = 'CHANGE_COLUMN_SIZE'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION'
