const data = [
  {
    id: 1,
    name: 'iPhone 12 Mini 64 GB',
    image: [
      '/img/iphone12-1.jpeg',
      '/img/iphone12-2.jpeg',
      '/img/iphone12-3.jpeg',
      '/img/iphone12-4.jpeg',
    ],
    description:
      'The iPhone 12 features a 6.1-inch (15 cm) display with Super Retina XDR OLED technology at a resolution of 2532×1170 pixels and a pixel density of about 460 ppi. The iPhone 12 Mini features a 5.4-inch (14 cm) display with the same technology at a resolution of 2340×1080 pixels and a pixel density of about 476 ppi.',
    brand: 'Apple',
    category: 'smartphone',
    price: 729,
    countInStock: 5,
    rating: 4.7,
    numOfReviews: 102,
    shippingType: 'fast',
  },
  {
    id: 2,
    name: 'iPhone SE 64 GB',
    image: [
      '/img/iphonese-1.jpeg',
      '/img/iphonese-2.jpeg',
      '/img/iphonese-3.jpeg',
      '/img/iphonese-4.jpeg',
    ],
    description:
      'he second-generation iPhone SE is a smartphone designed and developed by Apple Inc. It is part of the 13th generation of the iPhone, alongside the iPhone 11 and 11 Pro/Pro Max models.',
    brand: 'Apple',
    category: 'smartphone',
    price: 359,
    countInStock: 7,
    rating: 4.3,
    numOfReviews: 34,
    shippingType: 'standard',
  },
  {
    id: 3,
    name: 'Samsung S20 Plus 128 GB',
    image: [
      '/img/samsung-s20plus-1.jpeg',
      '/img/samsung-s20plus-2.jpeg',
      '/img/samsung-s20plus-3.jpeg',
      '/img/samsung-s20plus-4.jpeg',
    ],
    description:
      'Samsung Galaxy S20 Plus is released in Feb 2020 and comes in a dimension of 161.9 x 73.7 x 7.8 mm and it weighs 186 grams. The screen is a Dynamic AMOLED 2X capacitive touchscreen, which has a size of 6.7 inches.',
    brand: 'Samsung',
    category: 'smartphone',
    price: 750,
    countInStock: 10,
    rating: 4.6,
    numOfReviews: 53,
    shippingType: 'fast',
  },
  {
    id: 4,
    name: 'Samsung S21 Ultra 5G 128 GB',
    image: [
      '/img/samsung-s21-1.jpeg',
      '/img/samsung-s21-2.jpeg',
      '/img/samsung-s21-3.jpeg',
      '/img/samsung-s21-4.jpeg',
    ],
    description:
      "The Samsung Galaxy S21 Ultra 5G is the company's most premium smartphone yet, with a strong focus on cameras. Just like the Galaxy S20 Ultra, this new model boasts of 100X “space zoom” and 8K video recording, but with an improved shooting experience and even better image quality.",
    brand: 'Samsung',
    category: 'smartphone',
    price: 999,
    countInStock: 3,
    rating: 4.9,
    numOfReviews: 47,
    shippingType: 'fast',
  },
  {
    id: 5,
    name: 'Samsung Galaxy A21s 64 GB',
    image: [
      '/img/samsung-a21s-1.jpeg',
      '/img/samsung-a21s-2.jpeg',
      '/img/samsung-a21s-3.jpeg',
      '/img/samsung-a21s-4.jpeg',
    ],
    description:
      'The phone comes with a 6.50-inch touchscreen display with a resolution of 720x1600 pixels. Samsung Galaxy A21s is powered by a 2GHz octa-core Samsung Exynos 850 processor. It comes with 4GB of RAM. The Samsung Galaxy A21s runs Android 10 and is powered by a 5000mAh non-removable battery.',
    brand: 'Samsung',
    category: 'smartphone',
    price: 450,
    countInStock: 6,
    rating: 3.4,
    numOfReviews: 24,
    shippingType: 'standard',
  },
  {
    id: 6,
    name: 'Samsung Galaxy A51 2020 128 GB',
    image: [
      '/img/samsung-a51-1.jpeg',
      '/img/samsung-a51-2.jpeg',
      '/img/samsung-a51-3.jpeg',
      '/img/samsung-a51-4.jpeg',
    ],
    description:
      'The Samsung Galaxy A51 is an Android smartphone manufactured by Samsung Electronics as part of its Galaxy A series. It was announced and released in December 2019. The phone has a Super AMOLED FHD+ 6.5 in display, a 48 MP wide, 12 MP ultrawide, 5 MP depth, and 5 MP macro camera, a 4000 mAh battery, and an optical in-screen fingerprint sensor.',
    brand: 'Samsung',
    category: 'smartphone',
    price: 570,
    countInStock: 8,
    rating: 3.9,
    numOfReviews: 22,
    shippingType: 'fast',
  },
  {
    id: 7,
    name: 'Samsung Galaxy S20 128 GB',
    image: [
      '/img/samsung-s20-1.jpeg',
      '/img/samsung-s20-2.jpeg',
      '/img/samsung-s20-3.jpeg',
      '/img/samsung-s20-4.jpeg',
    ],
    description:
      'The phone comes with a 6.20-inch touchscreen display with a resolution of 1440x3200 pixels and an aspect ratio of 20:9. Samsung Galaxy S20 is powered by a 2GHz octa-core Samsung Exynos 990 processor that features 2 cores clocked at 2.73GHz, 2 cores clocked at 2.5GHz and 4 cores clocked at 2GHz. It comes with 8GB of RAM. The Samsung Galaxy S20 runs Android 10 and is powered by a 4000mAh non-removable battery. The Samsung Galaxy S20 supports wireless charging, as well as proprietary fast charging.',
    brand: 'Samsung',
    category: 'smartphone',
    price: 800,
    countInStock: 15,
    rating: 4.3,
    numOfReviews: 22,
    shippingType: 'fast',
  },
  {
    id: 8,
    name: 'Samsung Galaxy A21s 64 GB',
    image: [
      '/img/samsung-m31s-1.jpeg',
      '/img/samsung-m31s-2.jpeg',
      '/img/samsung-m31s-3.jpeg',
      '/img/samsung-m31s-4.jpeg',
    ],
    description:
      'Samsung has equipped the Galaxy M31 with an Exynos 9611 SoC and gets 6GB of RAM. It has two storage variants to choose from, 64GB and 128GB. The Galaxy M31 is a dual SIM device with support for 4G as well as VoLTE. It runs Samsung OneUI 2.0 on top of Android 10.',
    brand: 'Samsung',
    category: 'smartphone',
    price: 550,
    countInStock: 10,
    rating: 3.9,
    numOfReviews: 32,
    shippingType: 'standard',
  },
  {
    id: 9,
    name: 'Xiaomi Redmi 9c 64 GB',
    image: [
      '/img/redmi-9c-1.jpeg',
      '/img/redmi-9c-2.jpeg',
      '/img/redmi-9c-3.jpeg',
      '/img/redmi-9c-4.jpeg',
    ],
    description:
      'Xiaomi Redmi 9C smartphone runs on Android v10 (Q) operating system. The phone is powered by Octa core, 2.3 GHz, Cortex A53 processor. It runs on the MediaTek Helio G35 Chipset. It has 2 GB RAM and 32 GB internal storage.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 250,
    countInStock: 12,
    rating: 3.7,
    numOfReviews: 17,
    shippingType: 'fast',
  },
  {
    id: 10,
    name: 'Xiaomi Mi 10T Pro 256 GB',
    image: [
      '/img/mi-10t-pro-1.jpeg',
      '/img/mi-10t-pro-2.jpeg',
      '/img/mi-10t-pro-3.jpeg',
      '/img/mi-10t-pro-4.jpeg',
    ],
    description:
      'The display of the smartphone has a 144Hz refresh rate with an OLED screen type. The device is powered by Qualcomm Snapdragon 865 SoC or the Snapdragon 865 Plus chipset. The pro model consists of a 108 MP sensor on the rear side and fueled with a 5,000 mAh battery that will support fast charging.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 650,
    countInStock: 7,
    rating: 4.2,
    numOfReviews: 62,
    shippingType: 'standard',
  },
  {
    id: 11,
    name: 'Xiaomi Redmi Note 8 Pro 64 GB',
    image: [
      '/img/redmi-note8-pro-1.jpeg',
      '/img/redmi-note8-pro-2.jpeg',
      '/img/redmi-note8-pro-3.jpeg',
      '/img/redmi-note8-pro-4.jpeg',
    ],
    description:
      'Xiaomi Redmi Note 8 Pro is powered by the Mediatek Helio G90T, Octa-core (2x Cortex-A76 + 6x Cortex-A55) processor. The smartphone comes with a 6.53 inches IPS LCD and 1080 x 2340 pixels resolution. The screen of the device is protected by Corning Gorilla Glass 5.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 300,
    countInStock: 6,
    rating: 3.9,
    numOfReviews: 8,
    shippingType: 'fast',
  },
  {
    id: 12,
    name: 'Xiaomi Redmi Note 10 64GB',
    image: [
      '/img/redmi-note10-1.jpeg',
      '/img/redmi-note10-2.jpeg',
      '/img/redmi-note10-3.jpeg',
      '/img/redmi-note10-4.jpeg',
    ],
    description:
      'The phone comes with a 6.47-inch touchscreen display with a resolution of 1080x2340 pixels. Xiaomi Mi Note 10 is powered by a 2.2GHz octa-core Qualcomm Snapdragon 730G processor. It comes with 6GB of RAM. The Xiaomi Mi Note 10 runs Android 9 and is powered by a 5260mAh non-removable battery. The Xiaomi Mi Note 10 supports proprietary fast charging.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 375,
    countInStock: 9,
    rating: 4,
    numOfReviews: 71,
    shippingType: 'fast',
  },
  {
    id: 13,
    name: 'Xiaomi Redmi Note 7 64 GB',
    image: [
      '/img/redmi-note7-1.jpeg',
      '/img/redmi-note7-2.jpeg',
      '/img/redmi-note7-3.jpeg',
      '/img/redmi-note7-4.jpeg',
    ],
    description:
      'Xiaomi Redmi Note 7 is powered by the Qualcomm SDM660 Snapdragon 660 Octa-core (4×2.2 GHz Kryo 260 + 4×1.8 GHz Kryo 260) processor. The smartphone comes with a 6.3 inches IPS LCD capacitive touchscreen and 1080 x 2340 pixels resolution. The screen of the device is protected by Corning Gorilla Glass 5. The rear camera consists of a 48 MP (wide) + 5 MP depth sensor or 12 MP (wide) + 2 MP depth sensor lenses.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 300,
    countInStock: 6,
    rating: 3.9,
    numOfReviews: 27,
    shippingType: 'standard',
  },
  {
    id: 14,
    name: 'Xiaomi Redmi 9T 64 GB',
    image: [
      '/img/redmi-9t-1.jpeg',
      '/img/redmi-9t-2.jpeg',
      '/img/redmi-9t-3.jpeg',
      '/img/redmi-9t-4.jpeg',
    ],
    description:
      'The phone comes with a 6.53-inch touchscreen display with a resolution of 1080x2340 pixels and an aspect ratio of 19.5:9.Redmi 9T comes with 4GB of RAM. The Redmi 9T runs Android 10 and is powered by a 6000mAh battery. The Redmi 9T supports proprietary fast charging.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 300,
    countInStock: 7,
    rating: 3.8,
    numOfReviews: 19,
    shippingType: 'fast',
  },
  {
    id: 15,
    name: 'Xiaomi Mi Note 10 Lite 128 GB 8 GB Ram',
    image: [
      '/img/mi-note10-lite-1.jpeg',
      '/img/mi-note10-lite-2.jpeg',
      '/img/mi-note10-lite-3.jpeg',
      '/img/mi-note10-lite-4.jpeg',
    ],
    description:
      'The phone comes with a 6.47-inch touchscreen display with a resolution of 1080x2340 pixels. Xiaomi Mi Note 10 Lite is powered by a 2.2GHz octa-core Qualcomm Snapdragon 730G processor. It comes with 6GB of RAM. The Xiaomi Mi Note 10 Lite runs Android 10 and is powered by a 5260mAh non-removable battery. The Xiaomi Mi Note 10 Lite supports proprietary fast charging.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 675,
    countInStock: 11,
    rating: 4.1,
    numOfReviews: 15,
    shippingType: 'fast',
  },
  {
    id: 16,
    name: 'Xiaomi Mi 9T 64 GB',
    image: [
      '/img/mi-9t-1.jpeg',
      '/img/mi-9t-2.jpeg',
      '/img/mi-9t-3.jpeg',
      '/img/mi-9t-4.jpeg',
    ],
    description:
      'The phone comes with a 6.39-inch touchscreen display with a resolution of 1080x2340 pixels and an aspect ratio of 19.5:9. Mi 9T is powered by a 1.8GHz octa-core Qualcomm Snapdragon 730 processor that features 6 cores clocked at 1.8GHz and 2 cores clocked at 2.2GHz. It comes with 6GB of RAM. The Mi 9T runs Android Pie and is powered by a 4000mAh battery. The Mi 9T supports proprietary fast charging.',
    brand: 'Xiaomi',
    category: 'smartphone',
    price: 400,
    countInStock: 7,
    rating: 4.3,
    numOfReviews: 14,
    shippingType: 'standard',
  },
  {
    id: 17,
    name: 'Samsung Galaxy Tab SM-T510 32GB 10.1" Tablet',
    image: ['/img/galaxy-tab-t510-1.jpeg', '/img/galaxy-tab-t510-2.jpeg'],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Samsung',
    category: 'tablet',
    price: 215,
    countInStock: 21,
    rating: 3.2,
    numOfReviews: 16,
    shippingType: 'standard',
  },
  {
    id: 18,
    name: 'Apple iPad Pro 5th Gen Wi-Fi Cellular 128 GB Tablet',
    image: [
      '/img/ipad-pro-5th-gen-1.jpeg',
      '/img/ipad-pro-5th-gen-2.jpeg',
      '/img/ipad-pro-5th-gen-3.jpeg',
      '/img/ipad-pro-5th-gen-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Apple',
    category: 'tablet',
    price: 1250,
    countInStock: 22,
    rating: 4.8,
    numOfReviews: 102,
    shippingType: 'fast',
  },
  {
    id: 19,
    name: 'Samsung Galaxy Tab A 8 SM-T290 32GB',
    image: [
      '/img/galaxy-tab-t290-1.jpeg',
      '/img/galaxy-tab-t290-2.jpeg',
      '/img/galaxy-tab-t290-3.jpeg',
      '/img/galaxy-tab-t290-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Samsung',
    category: 'tablet',
    price: 180,
    countInStock: 43,
    rating: 3.1,
    numOfReviews: 155,
    shippingType: 'standard',
  },
  {
    id: 20,
    name: 'Apple iPad 8th Gen 32 GB 10.2" WiFi Tablet',
    image: [
      '/img/ipad-8th-gen-1.jpeg',
      '/img/ipad-8th-gen-2.jpeg',
      '/img/ipad-8th-gen-3.jpeg',
      '/img/ipad-8th-gen-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Apple',
    category: 'tablet',
    price: 499,
    countInStock: 21,
    rating: 4.3,
    numOfReviews: 62,
    shippingType: 'fast',
  },
  {
    id: 21,
    name: 'Lenovo TAB TB-X306F 64 GB 10,1" Tablet',
    image: [
      '/img/lenovo-tab-x306f-1.jpeg',
      '/img/lenovo-tab-x306f-2.jpeg',
      '/img/lenovo-tab-x306f-3.jpeg',
      '/img/lenovo-tab-x306f-4.jpeg',
      '/img/lenovo-tab-x306f-5.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Lenovo',
    category: 'tablet',
    price: 289,
    countInStock: 12,
    rating: 3.3,
    numOfReviews: 21,
    shippingType: 'standard',
  },
  {
    id: 22,
    name: 'Samsung Galaxy Tab A7 SM-T500 32 GB 10.4" Tablet',
    image: [
      '/img/galaxy-tab-t500-1.jpeg',
      '/img/galaxy-tab-t500-2.jpeg',
      '/img/galaxy-tab-t500-3.jpeg',
      '/img/galaxy-tab-t500-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Samsung',
    category: 'tablet',
    price: 279,
    countInStock: 34,
    rating: 3.9,
    numOfReviews: 31,
    shippingType: 'standard',
  },
  {
    id: 23,
    name: 'Apple iPad Air 4th Gen 10.9" 256 GB WiFi Cellular Tablet',
    image: [
      '/img/ipad-air-4th-gen-1.jpeg',
      '/img/ipad-air-4th-gen-2.jpeg',
      '/img/ipad-air-4th-gen-3.jpeg',
      '/img/ipad-air-4th-gen-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Apple',
    category: 'tablet',
    price: 799,
    countInStock: 10,
    rating: 4.4,
    numOfReviews: 87,
    shippingType: 'fast',
  },
  {
    id: 24,
    name: 'Lenovo Yoga Smart TAB TB-X705F 64GB 10.1" IPS Tablet',
    image: [
      '/img/yoga-tab-x705f-2.jpeg',
      '/img/yoga-tab-x705f-3.jpeg',
      '/img/yoga-tab-x705f-4.jpeg',
      '/img/yoga-tab-x705f-5.jpeg',
      '/img/yoga-tab-x705f-6.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Lenovo',
    category: 'tablet',
    price: 449,
    countInStock: 11,
    rating: 4.1,
    numOfReviews: 24,
    shippingType: 'standard',
  },
  {
    id: 25,
    name: 'Huawei Matepad T10 32 GB',
    image: [
      '/img/huawei-matepad-t10-1.jpeg',
      '/img/huawei-matepad-t10-2.jpeg',
      '/img/huawei-matepad-t10-3.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Huawei',
    category: 'tablet',
    price: 289,
    countInStock: 9,
    rating: 4,
    numOfReviews: 7,
    shippingType: 'standard',
  },
  {
    id: 26,
    name: 'Asus ROG Strix G513QM-HN081T',
    image: [
      '/img/rog-g513qm-1.jpeg',
      '/img/rog-g513qm-2.jpeg',
      '/img/rog-g513qm-3.jpeg',
      '/img/rog-g513qm-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Asus',
    category: 'computer',
    price: 1975,
    countInStock: 9,
    rating: 4.6,
    numOfReviews: 4,
    shippingType: 'standard',
  },
  {
    id: 27,
    name: 'Asus Tuf Gaming FX706LI-HX175',
    image: [
      '/img/tuf-gaming-fx706li-1.jpeg',
      '/img/tuf-gaming-fx706li-2.jpeg',
      '/img/tuf-gaming-fx706li-3.jpeg',
      '/img/tuf-gaming-fx706li-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Asus',
    category: 'computer',
    price: 989,
    countInStock: 19,
    rating: 4.3,
    numOfReviews: 11,
    shippingType: 'fast',
  },
  {
    id: 28,
    name: 'Asus X515JF-BQ036',
    image: [
      '/img/asus-x515jf-1.jpeg',
      '/img/asus-x515jf-2.jpeg',
      '/img/asus-x515jf-3.jpeg',
      '/img/asus-x515jf-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Asus',
    category: 'computer',
    price: 789,
    countInStock: 23,
    rating: 3.9,
    numOfReviews: 13,
    shippingType: 'standard',
  },
  {
    id: 29,
    name: 'Asus P5440FA-BM1235',
    image: [
      '/img/asus-p5440fa-1.jpeg',
      '/img/asus-p5440fa-2.jpeg',
      '/img/asus-p5440fa-3.jpeg',
      '/img/asus-p5440fa-4.jpeg',
      '/img/asus-p5440fa-5.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Asus',
    category: 'computer',
    price: 1080,
    countInStock: 16,
    rating: 4.2,
    numOfReviews: 17,
    shippingType: 'fast',
  },
  {
    id: 30,
    name: 'Asus ZenBook UX534FTC-A9076T',
    image: [
      '/img/zenbook-ux534ftc-1.jpeg',
      '/img/zenbook-ux534ftc-2.jpeg',
      '/img/zenbook-ux534ftc-3.jpeg',
      '/img/zenbook-ux534ftc-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Asus',
    category: 'computer',
    price: 2245,
    countInStock: 9,
    rating: 4.8,
    numOfReviews: 12,
    shippingType: 'fast',
  },
  {
    id: 31,
    name: 'HP Omen 15-DH0016NT',
    image: [
      '/img/hp-omen-1.jpeg',
      '/img/hp-omen-2.jpeg',
      '/img/hp-omen-3.jpeg',
      '/img/hp-omen-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Hp',
    category: 'computer',
    price: 1349,
    countInStock: 11,
    rating: 4.2,
    numOfReviews: 3,
    shippingType: 'standard',
  },
  {
    id: 32,
    name: 'Hp Elitebook X360 830',
    image: [
      '/img/hp-elitebook-x360-1.jpeg',
      '/img/hp-elitebook-x360-2.jpeg',
      '/img/hp-elitebook-x360-3.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Hp',
    category: 'computer',
    price: 1649,
    countInStock: 10,
    rating: 4,
    numOfReviews: 12,
    shippingType: 'fast',
  },
  {
    id: 33,
    name: 'Xiaomi RedmiBook',
    image: [
      '/img/xiaomi-redmibook-1.jpeg',
      '/img/xiaomi-redmibook-2.jpeg',
      '/img/xiaomi-redmibook-3.jpeg',
      '/img/xiaomi-redmibook-4.jpeg',
      '/img/xiaomi-redmibook-5.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Xiaomi',
    category: 'computer',
    price: 749,
    countInStock: 8,
    rating: 4.6,
    numOfReviews: 12,
    shippingType: 'fast',
  },
  {
    id: 34,
    name: 'Microsoft Surface Pro 6 ',
    image: [
      '/img/microsoft-surface-pro6-1.jpeg',
      '/img/microsoft-surface-pro6-2.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Microsoft',
    category: 'computer',
    price: 1349,
    countInStock: 8,
    rating: 4.7,
    numOfReviews: 11,
    shippingType: 'fast',
  },
  {
    id: 35,
    name: 'Lenovo V14 82C4011NTX',
    image: [
      '/img/lenovo-v14-1.jpeg',
      '/img/lenovo-v14-2.jpeg',
      '/img/lenovo-v14-3.jpeg',
      '/img/lenovo-v14-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Lenovo',
    category: 'computer',
    price: 689,
    countInStock: 18,
    rating: 4.1,
    numOfReviews: 5,
    shippingType: 'standard',
  },
  {
    id: 36,
    name: 'Lenovo V15 82C500NNTX',
    image: [
      '/img/lenovo-v15-1.jpeg',
      '/img/lenovo-v15-2.jpeg',
      '/img/lenovo-v15-3.jpeg',
      '/img/lenovo-v15-4.jpeg',
      '/img/lenovo-v15-5.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Lenovo',
    category: 'computer',
    price: 879,
    countInStock: 18,
    rating: 3.9,
    numOfReviews: 19,
    shippingType: 'fast',
  },
  {
    id: 37,
    name: 'Lenovo Flex 5 81X1008GTX',
    image: [
      '/img/lenovo-flex5-1.jpeg',
      '/img/lenovo-flex5-2.jpeg',
      '/img/lenovo-flex5-3.jpeg',
      '/img/lenovo-flex5-4.jpeg',
      '/img/lenovo-flex5-5.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Lenovo',
    category: 'computer',
    price: 1079,
    countInStock: 9,
    rating: 4.3,
    numOfReviews: 25,
    shippingType: 'fast',
  },
  {
    id: 38,
    name: 'Dell XPS 9305',
    image: [
      '/img/xps-9305-1.jpeg',
      '/img/xps-9305-2.jpeg',
      '/img/xps-9305-3.jpeg',
      '/img/xps-9305-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Dell',
    category: 'computer',
    price: 1749,
    countInStock: 13,
    rating: 4.5,
    numOfReviews: 21,
    shippingType: 'fast',
  },
  {
    id: 39,
    name: 'Dell Gaming G5',
    image: [
      '/img/dell-gaming-g5-1.jpeg',
      '/img/dell-gaming-g5-2.jpeg',
      '/img/dell-gaming-g5-3.jpeg',
      '/img/dell-gaming-g5-4.jpeg',
    ],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nisl erat, molestie in maximus faucibus, efficitur vitae nisl. Quisque egestas diam enim, sed tempor ipsum ullamcorper at. In vestibulum vehicula nisi, eget egestas diam tempor et. Vestibulum tempus sit amet nibh ac sodales. Donec accumsan mi nulla, nec sagittis leo tincidunt et.',
    brand: 'Dell',
    category: 'computer',
    price: 1849,
    countInStock: 6,
    rating: 4.4,
    numOfReviews: 13,
    shippingType: 'fast',
  },
]

export default data
